spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/test/demodb
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true


  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  mvc:
    converters:
      preferred-json-mapper: gson
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB




